### ISSUE TITLE
Submit a PR to fzf.fish?

### ISSUE THREAD

**Issue by PatrickF1** [stdlo/dotfiles#1]
Hi there!

I'm the owner of [patrickf1/fzf.fish](https://github.com/PatrickF1/fzf.fish). I saw you forked it and made a valuable update in https://github.com/stdlo/fzf.fish. I don't know if you wanted to PR it in since I currently blocked PRs. Would you like me to open it up for you so you can open a PR and get that update upstream?

Thanks,
Patrick

(btw in case you were wondering why I opened an issue here, I have no idea how else to contact you)

**Comment by PatrickF1** [comment]
Tagging @stdlo to make sure a notification is sent

**Comment by stdlo** [comment]
If you would like the change upstream I'm happy for it to be a pr. Do you need me to request that on your repo?

**Comment by PatrickF1** [comment]
Did you want to make a PR? Sorry I sort of assumed you did since most people who fork prefer to make a PR upstream. If you didn't then no problem, I can just do it myself.
LMK and I can temporarily open it up for you.

**Comment by stdlo** [comment]
Sorry for the confusion! Yes please open a PR.

**Comment by PatrickF1** [comment]
Ok I've added you to as a collaborator on the repo so you can open the PR. Thanks :)
